services:
  mongodb:
    image: mongo:7-jammy

    container_name: mongodb
    
    ports:
      - "27007:27017"
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
    volumes:  
      - mongodata:/data/db
    
    networks:
      - backend
    
    restart: always

  pgvector:
    image: pgvector/pgvector:pg13
    
    container_name: pgvector
    
    ports:
      - "5555:5432"
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    volumes:
      - pgvector:/var/lib/postgresql/data
    
    networks:
      - backend
    
    restart: always
    
networks:
  backend:

volumes:
  mongodata:  
  pgvector: